default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: okr_manager_development
  username: postgres
  password: QB7StzzZE78i

test:
  <<: *default
  database: okr_manager_test
  username: postgres
  password: QB7StzzZE78i

production:
  <<: *default
  database: <%= ENV['RAILS_DATABASE_NAME'] %>
  username: <%= ENV['RAILS_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_DATABASE_USERPASSWORD'] %>
  host:  <%= ENV['RAILS_DATABASE_HOST'] %>
